apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
  labels:
    app: my-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "votesdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}   # simple in-memory storage, no persistence

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev
spec:
  selector:
    app: my-postgres
  ports:
    - port: 5432
      targetPort: 5432
